import {
  BarChart3,
  Users,
  ShoppingCart,
  TrendingUp,
  Settings,
  FileText,
  PieChart,
  Activity,
  Mail,
  Calendar,
  Database,
  Shield,
  DollarSign,
  Globe,
  MessageSquare,
  BookOpen,
  Target,
  Zap,
  Package,
  Home,
  Bell,
  HelpCircle,
  CreditCard,
  Tag,
  UserCheck,
  FileBarChart,
  Megaphone,
  Code,
  Layers,
  Cloud,
  Lock,
  Smartphone,
  Monitor,
  Tablet,
  type LucideIcon,
  TargetIcon,
  Calculator,
  User,
} from "lucide-react";
import { ContentType } from "@/types/content";

export interface SidebarItemConfig {
  title: string;
  contentId: ContentType;
  icon: LucideIcon;
  badge?: string;
  color: string;
  bgColor: string;
  isActive?: boolean;
  description?: string;
}

export interface SidebarSection {
  title: string;
  items: SidebarItemConfig[];
}

export const WEBSITE_TYPE_CONFIGS = {
  analytics: {
    icon: BarChart3,
    gradient: "bg-gradient-to-r from-blue-500 to-purple-600",
    primaryColor: "blue",
    sections: [
      {
        title: "Analytics Core",
        items: [
           {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Main dashboard overview",
          },
           {
            title: "Site User Count",
            contentId: "site-count-db1" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "GAnalytics",
          },
           {
            title: "Country, City Track",
            contentId: "country-db1" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Users Visiting",
          },
          
        ]
        },
      {
        title: "Data",
        items: [
         {
            title: "All Users",
            contentId: "analytics-users-db1" as ContentType,
            icon: User,
            badge: null,
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Registered users",
          },
          {
            title: "All Subscribed Users",
            contentId: "analytics-subscribed-db1" as ContentType,
            icon: User,
            badge: null,
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Subscribed users",
          },
          {
            title: "All Blogs Categories",
            contentId: "analytics-blogCat" as ContentType,
            icon: Globe,
            badge: null,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Many Blog Categories",
          },
          {
            title: "All Blogs",
            contentId: "analytics-blogs" as ContentType,
            icon: Users,
            badge: null,
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "Blogs On IndiaESG",
          },
           {
            title: "All Magazines",
            contentId: "analytics-magazines" as ContentType,
            icon: Users,
            badge: null,
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "Magazine and count",
          },
        ],
      },
    ],
  },
  scr: {
    icon: TargetIcon,
    gradient: "bg-gradient-to-r from-green-500 to-emerald-600",
    primaryColor: "green",
    sections: [
      {
        title: "Analytics",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Store overview",
          },
           {
            title: "Track Dashboard",
            contentId: "dashboard-db2" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Blog overview",
          },
          {
            title: "Site User Count",
            contentId: "site-count-db2" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "GAnalytics",
          },
           {
            title: "Country, City Track",
            contentId: "country-db2" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Users Visiting",
          },
          {
            title: "Track Registration",
            contentId: "db2-reg-track" as ContentType,
            icon: ShoppingCart,
            color: "text-green-600 dark:text-green-400",
            bgColor: "bg-green-50 dark:bg-green-950/50",
            description: "Order management",
          },
          {
            title: "Track Countries",
            contentId: "db2-CountryChart" as ContentType,
            icon: Database,
            color: "text-red-600 dark:text-red-400",
            bgColor: "bg-red-50 dark:bg-red-950/50",
            description: "Stock management",
          },
           {
            title: "Track SCR Results",
            contentId: "db2-scr-stats" as ContentType,
            icon: Database,
            color: "text-red-600 dark:text-red-400",
            bgColor: "bg-red-50 dark:bg-red-950/50",
            description: "Stock management",
          },
           {
            title: "Track Learning Obj Results",
            contentId: "db2-lo-stats" as ContentType,
            icon: Database,
            color: "text-red-600 dark:text-red-400",
            bgColor: "bg-red-50 dark:bg-red-950/50",
            description: "Stock management",
          },
        ],
      },
      {
        title: "Data",
        items: [
          {
            title: "All Users",
            contentId: "db2-usertable" as ContentType,
            icon: DollarSign,
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Sales performance",
          },
           {
            title: "All Contact Messages",
            contentId: "db2-contact" as ContentType,
            icon: DollarSign,
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Sales performance",
          },
          {
            title: "Learning Obj Questions",
            contentId: "db2-lo" as ContentType,
            icon: Users,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Customer analytics",
          },
          {
            title: "SCR Questions",
            contentId: "db2-scr" as ContentType,
            icon: Tag,
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "Discount management",
          },
          {
            title: "Flash Titles",
            contentId: "db2-flash" as ContentType,
            icon: Megaphone,
            color: "text-pink-600 dark:text-pink-400",
            bgColor: "bg-pink-50 dark:bg-pink-950/50",
            description: "Marketing campaigns",
          },
          {
            title: "Flash Questions",
            contentId: "db2-flash-question" as ContentType,
            icon: Megaphone,
            color: "text-pink-600 dark:text-pink-400",
            bgColor: "bg-pink-50 dark:bg-pink-950/50",
            description: "Marketing campaigns",
          },
          {
            title: "Notes",
            contentId: "db2-note" as ContentType,
            icon: Megaphone,
            color: "text-pink-600 dark:text-pink-400",
            bgColor: "bg-pink-50 dark:bg-pink-950/50",
            description: "Marketing campaigns",
          },
        ],
      },
    ],
  },
  olympiad: {
    icon: BookOpen,
    gradient: "bg-gradient-to-r from-orange-500 to-red-600",
    primaryColor: "orange",
    sections: [
      {
        title: "Analytics",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Blog overview",
          },
          {
            title: "Site User Count",
            contentId: "site-count-db3" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "GAnalytics",
          },
           {
            title: "Country, City Track",
            contentId: "country-db3" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Users Visiting",
          },
          {
            title: " Goals Completion",
            contentId: "goal-completion" as ContentType,
            icon: Tag,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Content categories",
          },
          {
            title: " All Goals Completion",
            contentId: "all-goal-completion" as ContentType,
            icon: Tag,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Content categories",
          },
          {
            title: "Track Class",
            contentId: "track-class" as ContentType,
            icon: Tag,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Content categories",
          },
          // {
          //   title: "Track Countries",
          //   contentId: "countries-db3" as ContentType,
          //   icon: Tag,
          //   color: "text-purple-600 dark:text-purple-400",
          //   bgColor: "bg-purple-50 dark:bg-purple-950/50",
          //   description: "Content categories",
          // },
          // {
          //   title: "Track Results",
          //   contentId: "results-db3" as ContentType,
          //   icon: FileText,
          //   color: "text-indigo-600 dark:text-indigo-400",
          //   bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
          //   description: "Image and file management",
          // },
          {
            title: "Track Certifications",
            contentId: "certification" as ContentType,
            icon: FileText,
            color: "text-indigo-600 dark:text-indigo-400",
            bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
            description: "Image and file management",
          },
          {
            title: "Track Payments",
            contentId: "payments_db3" as ContentType,
            icon: FileText,
            color: "text-indigo-600 dark:text-indigo-400",
            bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
            description: "Image and file management",
          },
        ],
      },
      {
        title: "Data",
        items: [
          {
            title: "All Users",
            contentId: "users-db3" as ContentType,
            icon: MessageSquare,
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "Comment moderation",
          },
          // {
          //   title: "Questions",
          //   contentId: "question-db3" as ContentType,
          //   icon: Activity,
          //   color: "text-green-600 dark:text-green-400",
          //   bgColor: "bg-green-50 dark:bg-green-950/50",
          //   description: "Social engagement",
          // },
          // {
          //   title: "Goals",
          //   contentId: "goal-db3" as ContentType,
          //   icon: Mail,
          //   color: "text-purple-600 dark:text-purple-400",
          //   bgColor: "bg-purple-50 dark:bg-purple-950/50",
          //   description: "Email subscribers",
          // },
          // {
          //   title: "Goals Tests",
          //   contentId: "goal-test-db3" as ContentType,
          //   icon: Target,
          //   color: "text-pink-600 dark:text-pink-400",
          //   bgColor: "bg-pink-50 dark:bg-pink-950/50",
          //   description: "SEO optimization",
          // },
        ],
      },
    ],
  },
  computation: {
    icon: Calculator,
    gradient: "bg-gradient-to-r from-purple-500 to-pink-600",
    primaryColor: "purple",
    sections: [
      {
        title: "Analytics",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Platform overview",
          },
          {
            title: "Track Dashboard",
            contentId: "dashboard-db4" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Blog overview",
          },
          {
            title: "Site User Count",
            contentId: "site-count-db4" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "GAnalytics",
          },
           {
            title: "Country, City Track",
            contentId: "country-db4" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Users Visiting",
          },
          {
            title: "Track Registration",
            contentId: "db4-trackReg" as ContentType,
            icon: Users,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "Track users registrations",
          },
          {
            title: "Track Emissions",
            contentId: "db4-trackEmission" as ContentType,
            icon: CreditCard,
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "All Emissions",
          },
          {
            title: "All Users",
            contentId: "db4-users" as ContentType,
            icon: Users,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "User accounts",
          },
          {
            title: "All Emissions",
            contentId: "db4-emission" as ContentType,
            icon: Users,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "All Financed Emissions",
          },
        ],
      },
    ],
  },
} as const;

// export const COMMON_TOOLS = [
//   // {
//   //   title: "Calendar",
//   //   contentId: "tools-calendar" as ContentType,
//   //   icon: Calendar,
//   //   badge: "3",
//   //   color: "text-indigo-600 dark:text-indigo-400",
//   //   bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
//   //   description: "Scheduled events",
//   // },
//   // {
//   //   title: "Charts & Reports",
//   //   contentId: "tools-charts" as ContentType,
//   //   icon: PieChart,
//   //   badge: null,
//   //   color: "text-pink-600 dark:text-pink-400",
//   //   bgColor: "bg-pink-50 dark:bg-pink-950/50",
//   //   description: "Data visualization",
//   // },
//   // {
//   //   title: "Device Analytics",
//   //   contentId: "tools-devices" as ContentType,
//   //   icon: Monitor,
//   //   badge: "Multi",
//   //   color: "text-cyan-600 dark:text-cyan-400",
//   //   bgColor: "bg-cyan-50 dark:bg-cyan-950/50",
//   //   description: "Cross-device tracking",
//   // },
//   // {
//   //   title: "Settings",
//   //   contentId: "settings" as ContentType,
//   //   icon: Settings,
//   //   badge: null,
//   //   color: "text-gray-600 dark:text-gray-400",
//   //   bgColor: "bg-gray-50 dark:bg-gray-950/50",
//   //   description: "System configuration",
//   // },
// ];

// export const SUPPORT_ITEMS = [
//   // {
//   //   title: "Help Center",
//   //   contentId: "help" as ContentType,
//   //   icon: HelpCircle,
//   //   badge: null,
//   //   color: "text-blue-600 dark:text-blue-400",
//   //   bgColor: "bg-blue-50 dark:bg-blue-950/50",
//   //   description: "Documentation & guides",
//   // },
//   // {
//   //   title: "Notifications",
//   //   contentId: "notifications" as ContentType,
//   //   icon: Bell,
//   //   badge: "3",
//   //   color: "text-orange-600 dark:text-orange-400",
//   //   bgColor: "bg-orange-50 dark:bg-orange-950/50",
//   //   description: "System notifications",
//   // },
//   // {
//   //   title: "Feature Requests",
//   //   contentId: "feedback" as ContentType,
//   //   icon: Megaphone,
//   //   badge: "Vote",
//   //   color: "text-purple-600 dark:text-purple-400",
//   //   bgColor: "bg-purple-50 dark:bg-purple-950/50",
//   //   description: "Request new features",
//   // },
// ];
