import {
  BarChart3,
  Users,
  ShoppingCart,
  TrendingUp,
  Settings,
  FileText,
  PieChart,
  Activity,
  Mail,
  Calendar,
  Database,
  Shield,
  DollarSign,
  Globe,
  MessageSquare,
  BookOpen,
  Target,
  Zap,
  Package,
  Home,
  Bell,
  HelpCircle,
  CreditCard,
  Tag,
  UserCheck,
  FileBarChart,
  Megaphone,
  Code,
  Layers,
  Cloud,
  Lock,
  Smartphone,
  Monitor,
  Tablet,
  type LucideIcon,
  TargetIcon,
  Calculator,
} from "lucide-react";
import { ContentType } from "@/types/content";

export interface SidebarItemConfig {
  title: string;
  contentId: ContentType;
  icon: LucideIcon;
  badge?: string;
  color: string;
  bgColor: string;
  isActive?: boolean;
  description?: string;
}

export interface SidebarSection {
  title: string;
  items: SidebarItemConfig[];
}

export const WEBSITE_TYPE_CONFIGS = {
  analytics: {
    icon: BarChart3,
    gradient: "bg-gradient-to-r from-blue-500 to-purple-600",
    primaryColor: "blue",
    sections: [
      {
        title: "Analytics Core",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Main dashboard overview",
          },
          {
            title: "Real-time Analytics",
            contentId: "analytics-realtime" as ContentType,
            icon: TrendingUp,
            badge: null,
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Live visitor tracking",
          },
          {
            title: "Traffic Sources",
            contentId: "analytics-traffic" as ContentType,
            icon: Globe,
            badge: null,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Traffic origin analysis",
          },
          {
            title: "User Journey",
            contentId: "analytics-users" as ContentType,
            icon: Users,
            badge: null,
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "User behavior patterns",
          },
        ],
      },
      {
        title: "Reports & Insights",
        items: [
          {
            title: "Conversion Funnels",
            contentId: "analytics-conversions" as ContentType,
            icon: Target,
            badge: "Pro",
            color: "text-pink-600 dark:text-pink-400",
            bgColor: "bg-pink-50 dark:bg-pink-950/50",
            description: "Sales funnel analysis",
          },
          {
            title: "Custom Reports",
            contentId: "analytics-reports" as ContentType,
            icon: FileText,
            badge: null,
            color: "text-indigo-600 dark:text-indigo-400",
            bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
            description: "Generate custom reports",
          },
          {
            title: "A/B Testing",
            contentId: "analytics-testing" as ContentType,
            icon: FileBarChart,
            badge: "Beta",
            color: "text-cyan-600 dark:text-cyan-400",
            bgColor: "bg-cyan-50 dark:bg-cyan-950/50",
            description: "Split testing tools",
          },
        ],
      },
    ],
  },
  scr: {
    icon: TargetIcon,
    gradient: "bg-gradient-to-r from-green-500 to-emerald-600",
    primaryColor: "green",
    sections: [
      {
        title: "Store Management",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Store overview",
          },
          {
            title: "Orders",
            contentId: "ecommerce-orders" as ContentType,
            icon: ShoppingCart,
            badge: "47",
            color: "text-green-600 dark:text-green-400",
            bgColor: "bg-green-50 dark:bg-green-950/50",
            description: "Order management",
          },
          {
            title: "Products",
            contentId: "ecommerce-products" as ContentType,
            icon: Package,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "Product catalog",
          },
          {
            title: "Inventory",
            contentId: "ecommerce-inventory" as ContentType,
            icon: Database,
            badge: "Low",
            color: "text-red-600 dark:text-red-400",
            bgColor: "bg-red-50 dark:bg-red-950/50",
            description: "Stock management",
          },
        ],
      },
      {
        title: "Sales & Marketing",
        items: [
          {
            title: "Revenue Analytics",
            contentId: "ecommerce-revenue" as ContentType,
            icon: DollarSign,
            badge: "↗",
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Sales performance",
          },
          {
            title: "Customer Insights",
            contentId: "ecommerce-customers" as ContentType,
            icon: Users,
            badge: "1.2k",
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Customer analytics",
          },
          {
            title: "Promotions",
            contentId: "ecommerce-promotions" as ContentType,
            icon: Tag,
            badge: "5",
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "Discount management",
          },
          {
            title: "Marketing",
            contentId: "ecommerce-marketing" as ContentType,
            icon: Megaphone,
            badge: "New",
            color: "text-pink-600 dark:text-pink-400",
            bgColor: "bg-pink-50 dark:bg-pink-950/50",
            description: "Marketing campaigns",
          },
        ],
      },
    ],
  },
  olympiad: {
    icon: BookOpen,
    gradient: "bg-gradient-to-r from-orange-500 to-red-600",
    primaryColor: "orange",
    sections: [
      {
        title: "Content Management",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Blog overview",
          },
          {
            title: "Posts",
            contentId: "blog-posts" as ContentType,
            icon: BookOpen,
            badge: "Draft",
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "Manage blog posts",
          },
          {
            title: "Categories",
            contentId: "blog-categories" as ContentType,
            icon: Tag,
            badge: null,
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Content categories",
          },
          {
            title: "Media Library",
            contentId: "blog-media" as ContentType,
            icon: FileText,
            badge: "500+",
            color: "text-indigo-600 dark:text-indigo-400",
            bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
            description: "Image and file management",
          },
        ],
      },
      {
        title: "Engagement",
        items: [
          {
            title: "Comments",
            contentId: "blog-comments" as ContentType,
            icon: MessageSquare,
            badge: "12",
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "Comment moderation",
          },
          {
            title: "Social Media",
            contentId: "blog-social" as ContentType,
            icon: Activity,
            badge: "↗",
            color: "text-green-600 dark:text-green-400",
            bgColor: "bg-green-50 dark:bg-green-950/50",
            description: "Social engagement",
          },
          {
            title: "Newsletter",
            contentId: "blog-newsletter" as ContentType,
            icon: Mail,
            badge: "2.5k",
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Email subscribers",
          },
          {
            title: "SEO Tools",
            contentId: "blog-seo" as ContentType,
            icon: Target,
            badge: "Pro",
            color: "text-pink-600 dark:text-pink-400",
            bgColor: "bg-pink-50 dark:bg-pink-950/50",
            description: "SEO optimization",
          },
        ],
      },
    ],
  },
  computation: {
    icon: Calculator,
    gradient: "bg-gradient-to-r from-purple-500 to-pink-600",
    primaryColor: "purple",
    sections: [
      {
        title: "Platform Overview",
        items: [
          {
            title: "Dashboard",
            contentId: "dashboard" as ContentType,
            icon: Home,
            badge: null,
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            isActive: true,
            description: "Platform overview",
          },
          {
            title: "User Management",
            contentId: "saas-users" as ContentType,
            icon: Users,
            badge: "2.4k",
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "User accounts",
          },
          {
            title: "Subscriptions",
            contentId: "saas-subscriptions" as ContentType,
            icon: CreditCard,
            badge: "Active",
            color: "text-emerald-600 dark:text-emerald-400",
            bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
            description: "Billing management",
          },
          {
            title: "API Usage",
            contentId: "saas-api" as ContentType,
            icon: Code,
            badge: "Live",
            color: "text-orange-600 dark:text-orange-400",
            bgColor: "bg-orange-50 dark:bg-orange-950/50",
            description: "API monitoring",
          },
        ],
      },
      {
        title: "Operations",
        items: [
          {
            title: "Performance",
            contentId: "saas-performance" as ContentType,
            icon: Zap,
            badge: "99.9%",
            color: "text-yellow-600 dark:text-yellow-400",
            bgColor: "bg-yellow-50 dark:bg-yellow-950/50",
            description: "System performance",
          },
          {
            title: "Infrastructure",
            contentId: "saas-infrastructure" as ContentType,
            icon: Cloud,
            badge: "Healthy",
            color: "text-blue-600 dark:text-blue-400",
            bgColor: "bg-blue-50 dark:bg-blue-950/50",
            description: "Cloud infrastructure",
          },
          {
            title: "Security",
            contentId: "saas-security" as ContentType,
            icon: Shield,
            badge: "Secure",
            color: "text-red-600 dark:text-red-400",
            bgColor: "bg-red-50 dark:bg-red-950/50",
            description: "Security monitoring",
          },
          {
            title: "Integrations",
            contentId: "saas-integrations" as ContentType,
            icon: Layers,
            badge: "24",
            color: "text-purple-600 dark:text-purple-400",
            bgColor: "bg-purple-50 dark:bg-purple-950/50",
            description: "Third-party integrations",
          },
        ],
      },
    ],
  },
} as const;

export const COMMON_TOOLS = [
  {
    title: "Calendar",
    contentId: "tools-calendar" as ContentType,
    icon: Calendar,
    badge: "3",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/50",
    description: "Scheduled events",
  },
  {
    title: "Charts & Reports",
    contentId: "tools-charts" as ContentType,
    icon: PieChart,
    badge: null,
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-50 dark:bg-pink-950/50",
    description: "Data visualization",
  },
  {
    title: "Device Analytics",
    contentId: "tools-devices" as ContentType,
    icon: Monitor,
    badge: "Multi",
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-50 dark:bg-cyan-950/50",
    description: "Cross-device tracking",
  },
  {
    title: "Settings",
    contentId: "settings" as ContentType,
    icon: Settings,
    badge: null,
    color: "text-gray-600 dark:text-gray-400",
    bgColor: "bg-gray-50 dark:bg-gray-950/50",
    description: "System configuration",
  },
];

export const SUPPORT_ITEMS = [
  {
    title: "Help Center",
    contentId: "help" as ContentType,
    icon: HelpCircle,
    badge: null,
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 dark:bg-blue-950/50",
    description: "Documentation & guides",
  },
  {
    title: "Notifications",
    contentId: "notifications" as ContentType,
    icon: Bell,
    badge: "3",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-50 dark:bg-orange-950/50",
    description: "System notifications",
  },
  {
    title: "Feature Requests",
    contentId: "feedback" as ContentType,
    icon: Megaphone,
    badge: "Vote",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 dark:bg-purple-950/50",
    description: "Request new features",
  },
];
